name_experiment: 2branch_top_down_mapping
model:
    arch: 2branch
    finetune: False
    n_obj_classes: 21
    ego_feature_dim: 64
    mem_feature_dim: 256
    mem_update: replace
    ego_downsample: False
    in_channels: 64
    out_channels: 64
    mid_channel: 64
data:
    train_split: train
    val_split: val
    test_split: test
    root: /hkfs/work/workspace/scratch/tp9819-trans4map/dataset_zteng/trans4map_baseline
    ego_downsample: False
    feature_type: lastlayer
training:
    train_epoch: 50
    batch_size: 16
    n_workers: 8
    print_interval: 20
    optimizer:
        lr:  0.00003
        # lr: 0.00003
        betas: [0.9, 0.999]
        weight_decay: 0.003
        # weight_decay: 0.01

    scheduler:
        lr_decay_rate: 0.8
        lr_epoch_per_decay: 20
    resume: #runs/gru_fullrez_lastlayer_m256/fuse/smnet_mp3d_best_model.pkl
    load_model: #runs/gru_fullrez_lastlayer_m256/54731/smnet_mp3d_best_model.pkl
seed: 9876