name_experiment: model_pano_segformer
model:
    arch: smnet
    finetune: False
    n_obj_classes: 20
    ego_feature_dim: 64
    mem_feature_dim: 128
    # mem_update: replace
    # ego_downsample: False
    pano_h: 512
    pano_w: 1024
    batch_size_every_processer: 1
    num_head: 4
    num_point: 4
    sampling_offsets: 1
    #sampling_offsets : 0.03
    

data:
    train_split: train
    val_split: val
    test_split: test
    # root: /hkfs/work/workspace/scratch/tp9819-trans4map/dataset_zteng/trans4map_baseline
    # root: /hkfs/work/workspace/scratch/tp9819-ws/datasets_zteng/hoho_data
    # root: /cvhci/data/VisLoc/zteng/trans4map_baseline
    root : /cvhci/temp/zteng/hoho_data/

    # ego_downsample: False
    # feature_type: lastlayer

training:
    train_epoch: 60
    batch_size: 4
    n_workers: 4
    print_interval: 10
    optimizer:
        lr:  0.00006
        # lr:  0.00006
        betas: [0.9, 0.999]
        weight_decay: 0.001
    scheduler:
        lr_decay_rate: 0.8
        lr_epoch_per_decay: 20
    resume: #runs/gru_fullrez_lastlayer_m256/fuse/smnet_mp3d_best_model.pkl
    load_model: #runs/gru_fullrez_lastlayer_m256/54731/smnet_mp3d_best_model.pkl
seed: 9876
